
* ToDo
- Factor out logging to a separate classxf
- Rewrite TLS-ENDPOINT to adjustable arrays and buffer pool, and check impact on
  speed/allocations. Possibly merge QUEUE-FRAME-REGION code for buffered connection
  and for the poll server.
- Use autoload to load stuff on-demand. Both to reduce size and to be able to call non-quicklisped libraries.
- Fix:  QUEUE-FRAME-REGION needs simple vectors as login.
- Make condition class for [[file:core/frames/headers.lisp::;; 20240718 TODO: make class for this connection error][incomplete header]] and for R being set.

* Implemented

** Class hierarchy changes
- HTTP-ERROR-STREAM now inherits from ERROR (used to be WARNING). You may need to adapt your handlers.
- Both stream and condition errors now inherit HTTP2-CONDITION.
- New class VANILLA-HTTP2-STREAM to cover data

** Logging
- *log-stream* :: moved variable
- log-closed-stream :: moved function

** Introspection
- GET-CONNECTIONS :: new generic functions on dispatchers. Intended for monitoring and tracking.

** Efficiency changes
- Some functions are declared globally to enable optimization
- Buffer pool is introduced (but not used)  - contributed by John Mallery
- PROCESS-PENDING-FRAMES now allocates reusable buffer for headers - contributed by John Mallery

** Frames are sent with less consing

- New frame queuing function QUEUE-FRAME-REGION for more efficient data flow.
- Frame writes now do not merge header and payload; they send both parts independently.
- Frame writing functions do not return the octet vector now. This was never
  promised, but some tests were to be modified.

** Window management
- New function: AVAILABLE-WINDOW-SIZE
- Window management is now part of HTTP/2 stream class.
- Reuse MAYBE-GROW-BUFFER

** Printing and reporting
- Improved error reporting texts.

** Documentation
- Some mixins were converted to standard format ("Does XXX")
- Better documentation of openssl wrapper

** OpenSSL
- SSL state was moved to the OPENSSL wrapper.
- SSL states were cleaned up (merged CAN-READ-SSL and NEG-BIO-NEEDS-READ)
- Some generic SSL handling code was factored away from the poll server: READ-ENCRYPTED-FROM-OPENSSL*, WRITE-OCTETS-TO-DECRYPT*, MAYBE-INIT-SSL, SSL-READ, SSL-PEEK, HANDLE-SSL-ERRORS*

** Tests
- BUFFERED-OUTPUT/TEST :: Test that buffered streams split the payload as expected
- Test for SSL were modified to handle changes
-  ::

** Other
- Client http connection now uses QUEUE-DATA-FRAME to send client preface.Previously it wrote directly to a network stream that does not have to exist.
- Slots of tls-endpoint-core are now invalidated after free.
- Pseudo-header slots move from server stream to vanilla stream to be able to print them for debuggin purposes.
- Network streams now have NIL as the stream by default to simplify PRINC.

** Removed internal functions
concatenate*
# Local Variables:
# org-hide-emphasis-markers: nil
# END:
