#!/bin/bash

set -e
# Clone so that we work on the staged version
rm -rf to-test
git worktree prune
git branch -D to-test || true
git worktree add to-test
git diff --cached |patch -p1 -d to-test

# Test that it works with real ecosystem
set -x
cd to-test
sbcl --script scaffolding/do-all-tests.lisp
